"use client";

import { useState } from "react";

import { Button, CopyButton, Dialog, Facts, Notice, Panel, Spinner } from "@/components/flick/ui";
import { ADMIN_ERROR_TEXT, useAdmin } from "@/lib/use-admin";
import type { Invite } from "@/lib/types";

/** The link contains the signing key, so it stays masked until asked for. */
function mask(url: string): string {
  const i = url.indexOf("#k=");
  return i < 0 ? url : `${url.slice(0, i)}#k=${"•".repeat(24)}`;
}

function QrCode({ rows }: { rows: string[] }) {
  const n = rows.length;
  const quiet = 4;
  const size = n + quiet * 2;
  return (
    <svg viewBox={`0 0 ${size} ${size}`} role="img" aria-label="QR code of the invitation link" shapeRendering="crispEdges">
      <rect width={size} height={size} fill="#fff" />
      {rows.map((row, r) =>
        [...row].map((c, col) =>
          c === "1" ? <rect key={`${r}-${col}`} x={col + quiet} y={r + quiet} width={1} height={1} fill="#000" /> : null,
        ),
      )}
    </svg>
  );
}

export function InvitePanel() {
  // The invitation only changes on rotation or restart: a slow refresh is plenty.
  const { data, error, loading } = useAdmin<Invite>("invite", 30_000);
  const [revealed, setRevealed] = useState(false);
  const [qr, setQr] = useState(false);

  return (
    <Panel title="Invitation link">
      {loading && !data && <Spinner label="Loading the invitation" />}
      {error && !data && <Notice tone="error">{ADMIN_ERROR_TEXT[error]}</Notice>}
      {data && (
        <>
          <p style={{ margin: 0, color: "var(--muted-foreground)", lineHeight: 1.6 }}>
            Paste this one link into Flick to connect it to this server. It carries the address and the signing key.
          </p>
          <pre className="invite-link" data-masked={revealed ? undefined : ""} aria-label="Invitation link">
            {revealed ? data.url : mask(data.url)}
          </pre>
          <div className="row-actions">
            <CopyButton text={data.url}>Copy Invite Link</CopyButton>
            <Button icon={revealed ? "eye-off" : "eye"} onClick={() => setRevealed((r) => !r)}>
              {revealed ? "Hide Link" : "Show Link"}
            </Button>
            {data.qr && (
              <Button icon="qr-code" onClick={() => setQr(true)}>
                Show QR Code
              </Button>
            )}
          </div>
          <Notice tone="info">
            This link contains the signing key. Share it only with the people you invite.
          </Notice>
          {data.address_guessed && (
            <Notice tone="warn">
              The address in this link is a guess ({data.address}). Set FLICKSYNC_PUBLIC_URL to your public address,
              for example https://sync.example.com, then restart FlickSync.
            </Notice>
          )}
          <Facts
            rows={[
              ["Address", data.address],
              ["Key", `${data.kid} · server ${data.server_id}`],
              ["Key source", data.key_source === "file" ? "Generated by FlickSync" : "Set in the environment"],
              ["Keys in use", String(data.key_count)],
            ]}
          />
          {data.key_source === "file" && (
            <p style={{ margin: 0, fontSize: "0.8125rem", color: "var(--muted-foreground)", lineHeight: 1.6 }}>
              To rotate the key, run <code>flicksync invite --rotate</code> on the server, then restart FlickSync. The
              previous key keeps working until you remove it.
            </p>
          )}
        </>
      )}
      {qr && data?.qr && (
        <Dialog
          title="Invitation QR code"
          description="Scan it with a device that has Flick. It contains the signing key."
          onClose={() => setQr(false)}
        >
          <div className="qr">
            <QrCode rows={data.qr} />
          </div>
        </Dialog>
      )}
    </Panel>
  );
}
