// Generates src/styles/tokens.css from the Flick design system's tokens.json
// (scripts/flick-tokens.json, exported from the "Flick" design system).
// Re-run `npm run tokens` after updating that file.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const t = JSON.parse(readFileSync(join(here, "flick-tokens.json"), "utf8"));
const theme = t.color.themes[0].id;

const lines = [];
const add = (name, value) => lines.push(`  --${name}: ${value};`);

for (const c of t.color.tokens) {
  const v = typeof c.value === "string" ? c.value : (c.value[theme] ?? Object.values(c.value)[0]);
  // Aliases are written as "{other-token}".
  add(c.name, v.replace(/^\{(.+)\}$/, "var(--$1)"));
}
for (const fam of ["spacing", "radius", "shadow", "blur", "scale"]) {
  for (const x of t[fam]?.tokens ?? []) add(x.name, x.value);
}
for (const [k, v] of Object.entries(t.type.families)) add(`font-${k}`, v);

const css = `/* Generated by scripts/gen-tokens.mjs from the Flick design system. Do not edit. */
@font-face {
  font-family: "Inter Variable";
  src: url("/fonts/inter-latin-opsz-normal.woff2") format("woff2");
  font-weight: 100 900;
  font-style: normal;
  font-display: swap;
}

:root {
  color-scheme: dark;
${lines.join("\n")}
}
`;
writeFileSync(join(here, "..", "src", "styles", "tokens.css"), css);
console.log(`tokens.css: ${lines.length} variables`);
